version: "3.8"

services:
  web:
    build: 
        context: .
    ports:
        - "8000:8000"
    volumes:
        - .:/app
     # - logvolume01:/var/log
    command: 
        sh -c "python manage.py runserver 0.0.0.0:8000"
#    links:
#        - redis
#  redis:
#    image: redis
#volumes:
#  logvolume01: {}