version: "3.8"

services:
  web:
    build: 
        context: .
    ports:
        - "8000:8000"
    volumes:
        - ./backend:/app
     # - logvolume01:/var/log
    command: 
        sh -c "python manage.py wait_for_db && python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=django_db
      - DB_USER=postgres
      - DB_PASS=postgres
    depends_on:
      - db
  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=django_db
      - POSTRGES_USER=postgres
      - POSTGRES_PASSWORD=postgres


  #    links:
  #        - redis
  #  redis:
  #    image: redis
  #volumes:
  #  logvolume01: {}